\documentclass{article}
\usepackage[inner=2cm,outer=2cm]{geometry}
\usepackage{hyperref}
\hypersetup{colorlinks=true}
\usepackage{dashrule}
\usepackage{authblk}
\usepackage{csquotes}
\usepackage{tikz}
\usepackage{framed}
\usepackage{color}
%\newenvironment{shadequote}%
%{\begin{snugshade}\begin{quote}}
%{\hfill\end{quote}\end{snugshade}}

%\definecolor{shadecolor}{rgb}{0.9,0.9,0.9}

\begin{document}

\title{TDM}
\author{Jeffrey A. Thompson}
\affil{Quantitative Biomedical Sciences Program, Geisel School of Medicine at Dartmouth College}
\maketitle

% !Rnw weave = knitr 
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{AnnotationParser}

<<setup-options, warning=FALSE, message=FALSE, echo=FALSE, results="hide">>=
library(TDM)
			
load_it("knitr")

# Set a few chunk options.
opts_chunk$set(cache=FALSE, 
				eval=TRUE, 
				warning=FALSE,
				message=FALSE,
				fig.width=5, 
				fig.height=5, 
				fig.align="center", 
				fig.path="figures/")
@

\section{Training Distribution Matching}

To perform the TDM transformation you need to have a reference dataset and a
target dataset. The reference dataset should be from microarray expression
experiments and the target dataset should be from RNA-seq. The target dataset
will be transformed to have similar characteristics to the reference.

As an example, the TDM package contains some sample data. These data can be
loaded as follows:

<<eval=TRUE>>=
data(meta)
data(tcga)
@

The data are loaded into variables \textbf{meta} and \textbf{tcga}. Here is a
summary of their characteristics:

<<eval=TRUE>>=
summary(as.vector(as.matrix(meta)))
summary(as.vector(as.matrix(tcga)))
@

If we simply scaled the TCGA data to be in the same range, the distribution
would be quite different:

<<>>=
load_it("scales")
tcga_vec = rescale(as.vector(as.matrix(tcga)), to=c(min(meta), max(meta)))
summary(tcga_vec)
@

One might try log transforming the RNA-seq data, but this also is
unsatisfactory:

<<>>=
load_it("data.table")
tcga_log = log_transform_p1(data.table(cbind(gene=rownames(tcga), tcga)))
summary(as.vector(data.matrix(tcga_log[,2:ncol(tcga_log),with=F])))
@

If we TDM transform the data, the results appear to be much improved:

<<>>=
tcga_tdm = tdm_transform(ref_data = data.table(cbind(gene=rownames(meta), meta)),
target_data = data.table(cbind(gene=rownames(tcga), tcga)))
summary(as.vector(data.matrix(tcga_tdm[,2:ncol(tcga_tdm),with=F])))
@

Finally, here is a plot comparing the distributions of the reference data, the
scaled data, the log transformed data, and the TDM transformed data:

<<comparison, include=FALSE>>=
load_it(c("reshape2", "lattice"))
meta_vec = as.vector(as.matrix(meta))
meta_dat = data.frame(
    cbind(values=meta_vec, dataset="META"))
tcga_scaled_dat = data.frame(
    cbind(values=tcga_vec, dataset="TCGA-SCALED"))
tcga_log_dat = data.frame(
    cbind(values=as.vector(
          data.matrix(tcga_log[,2:ncol(tcga_log),with=F])), 
          dataset="TCGA-LOG"))
tcga_tdm_dat = data.frame(
    cbind(values=as.vector(data.matrix(tcga_tdm[,2:ncol(tcga_tdm),with=F])), dataset="TCGA-TDM"))
all_data = melt(
    rbind(meta_dat, tcga_scaled_dat, tcga_log_dat, tcga_tdm_dat), value.name="values")

densityplot(
    ~as.numeric(as.character(values)), 
    data=all_data,groups=dataset, 
    ylim=c(0,.5), 
    auto.key=TRUE, 
    plot.points=FALSE, 
    main=paste0("Comparison of Scaling,\n",
        " Log, and TDM Transformation\n",
        " to the Reference Distribution"), 
    xlab="Log2 of Expression Value", 
    space="inside",
    bw="nrd0")
@

\begin{figure}
  \includegraphics{figures/comparison-1}
  \label{fig:comparison}
  \caption{TDM brings the sample RNA-seq data closest to the reference distribution. Log2 transformation creates a left-skewed distribution that is not typical of microarray data, making comparison between the datasets difficult, while simple scaling creates a right-skewed distribution.}
\end{figure}

\end{document}
